### ISSUE TITLE
Добавить ссылки на топики внутри топиков 

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/ros_course#6]
- [x] В сюда https://github.com/lsd-maddrive/ROS_course/blob/develop/topics/1_01_My_First_Package.md#%D0%BA%D0%B0%D0%BA-%D0%BC%D0%BD%D0%B5-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-workspace сслыку на https://github.com/lsd-maddrive/ROS_course/blob/develop/topics/0_01_Shell.md
- [x] В сюда https://github.com/lsd-maddrive/ROS_course/blob/develop/topics/1_02_Git_n_Package.md ссылку на https://github.com/lsd-maddrive/ROS_course/blob/develop/topics/0_02_Git_CLI.md

**Comment by KaiL4eK** [comment]
@serykhelena а для чего эти ссылки? Ведь люди видят топики - и указания вроде на топики ранее, которые они проходили

**Comment by KaiL4eK** [comment]
Done
