### ISSUE TITLE
Закончить топики

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/ros_course#7]
Topic 1_05 

- [x] дописать раздел Чему научились?
- [x] дополнить ресурсы (если нужно)

**Comment by KaiL4eK** [comment]
Я сейчас разогнался, много кросс фиксов, поэтому эти разделы буду писать после завершения первой части)

**Comment by serykhelena** [comment]
Topic 1_06 

- [ ] дополнить раздел "Чему научились"
- [ ] дополнить раздел "Вопросики" 
- [ ] дополнить раздел "Ресурсы" 


> На всякий случай оставлю такие комментарии, в конце можно будет проверить, что ничего не забыто (=

**Comment by serykhelena** [comment]
Topic 1_07 

- [ ] дополнить раздел "Чему научились" 
- [ ] дополнить раздел "Вопросики" 
- [ ] дополнить раздел "Ресурсы"

**Comment by KaiL4eK** [comment]
Убрал лишние разделы, часть выводов заменил на "Чему научились"
